### ISSUE TITLE
Unable to get the `batch_soax` command to work on Intel as well as M1 MacBook 

### ISSUE THREAD

**Issue by aaparikh** [tix209/SOAX#6]
After running the following command
```shell
./batch_soax -i ./select_test/ -s ./result-snakes/ -p default_prams.txt --ridge 0.001 0.005 0.1 --stretch 0.1 0.1 1.0
```
OR
```shell
./batch_soax -i ./select_test/ -s ./result-snakes/ -p default_prams.txt
```

where,
`select_test` - Is a folder containing isotropic images (5 of them)
`result-snakes` - Is an empty folder where all the resultant txt files containing information about snakes is to be stored.
`default_prams.txt` - file containing default parameter for execution.

I am getting the following error in the terminal
```shell
Input may contain multiple images.
dyld[11941]: missing symbol called
```

When I execute the following command for a single file, it executes properly and output in form of several text files is obtained.
```shell
#Sweeping parameter space on a single image
./batch soax -i ../data/image.mha -p ../parameters/parameter.txt -s ../result-snakes/ --ridge 0.001 0.005 0.1 --stretch 0.1 0.1 1.0
```

1. Why is it then not working for the batch of files (in a folder)?
2. What is the meaning of the error "Input may contain multiple images. dyld[11941]: missing symbol called"?
3. If I want to run this software on a lot of data how do I go about creating such process, should I leverage multiprocessing? Is there internal feature to do that optimally?

**Comment by vavylonis** [comment]
Issue resolved through email communications
